### PR TITLE
Add interactive functions Release

### PR DESCRIPTION
**Pull request by manq2010**
To-Do list: interactive list Project
---
In this release, the following was done:
* Added Methods to update complete task status
* Added checkbox method
* Implemented function for clearing checked tasks

### CODE REVIEW

**Review by leonardodiasb — CHANGES_REQUESTED** [review]
# Required Changes ♻️ ⚠️ 🚦 

Hi @manq2010, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

mario_ladders

## Good points 👍 

 - Professional PR message. ✔️
 - Correct use of Github flow. ✔️ 

## Aspects to improve ♻️

- [ ] Check the comments under the review.
- [ ] The UI design of your To-Do-List is great but I cannot test the required features from this project. Unfortunately when I open the app with `npm start` there is no list of tasks present so I cannot click in any task checkbox to test the status update and cannot use the 'Clear all complete' button. Kindly add an array of tasks and populate the UI with them, so it is possible for the next reviewer to test those features in this PR. PS: the add task function is not working, so I cannot add tasks to test those features. But this is a requirement for the next project so it is not a problem.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by bimbolabuari — COMMENTED** [review]
Hello @manq2010 👋,

_This is an additional review as a result of the second opinion request._

- Currently, am unable to implement any todo functionality such as adding, removing, or "Clear all completed" as required in this milestone and the previous one, kindly implement the change requested by the previous CR.

https://user-images.githubusercontent.com/66112760/199784447-a514ad6b-93d3-454b-92b4-ba87832beedf.mov




Keep rocking 🚀!

**Review by MaganaAsiati — APPROVED** [review]
# Status: Approved [✔️](https://emojipedia.org/check-mark/)
## Hi @manq2010 , I'm @MaganaAsiati , your reviewer for this PR  :wave: 
Great work on making the changes requested by a previous reviewer 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 





## Highlights
- Descriptive pull request :heavy_check_mark:👨🏻‍💻
- Descriptive README file  :heavy_check_mark:👨🏻‍💻
- Great work using the right GitHub Flow.:heavy_check_mark:
- No Linter errors :heavy_check_mark:


## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future.



Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
Cheers and Happy coding! 🤓 👏👏👏

**Comment by manq2010** [comment]
Noted and thanks @MaganaAsiati @bimbolabuari @leonardodiasb

**Pull request merged**
